### ISSUE TITLE
simple gallery not working

### ISSUE THREAD

**Issue by lillyfwang** [CUEWB/Uganda#3]

**Comment by nitesh201** [comment]
there's a surprise

**Comment by lillyfwang** [comment]
all @akalicki fault

**Comment by phanieste** [comment]
i found the problem. will push a fix!

**Comment by lillyfwang** [comment]
thanks!!!

**Comment by akalicki** [comment]
hahaha @nitesh201

**Comment by akalicki** [comment]
@phanieste what was the problem? was it a bug with the plugin or something we did on the website end?

**Comment by phanieste** [comment]
@akalicki Website. I put in a link on the nav-menu side of things that I think clashed with the js that does the page scrolling and crashed the javascript, so I just moved the link to social-links.
